name: my-test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: make lint

      - name: Run tests
        run: npm run test:coverage
      - name: Проверка покрытия
        run: |
          echo "Папка coverage:"
          ls -la coverage
          echo "Файл lcov.info (первые строки):"
          head -n 20 coverage/lcov.info

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
        args: >
          -Dsonar.projectKey=backend-project-46
          -Dsonar.organization=bugrich
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          -Dsonar.sources=src
